---
#################################
##    SWITCH AUTOMATIONS       ##
#################################

# Piano light on
alias: switch_xmas_lights_garden_on
trigger:
  platform: time
  at: input_datetime.xmas_light_start_time
condition:
    - condition: state
      entity_id: input_boolean.xmas_toggle
      state: 'on'
action:
  - service: light.turn_on
    entity_id:
      - light.shelly_shsw_1_1179e3
  - service: input_datetime.set_datetime
    entity_id: input_datetime.xmas_light_start_time
