---
#################################
##    SWITCH AUTOMATIONS       ##
#################################

# Piano light on
alias: switch_xmas_piano_lights_on
trigger:
  platform: time
  at: input_datetime.xmas_light_start_time
condition:
    - condition: state
      entity_id: input_boolean.xmas_toggle
      state: 'on'
action:
  - service: switch.turn_on
    entity_id:
      - switch.fritzschalter
  - service: input_datetime.set_datetime
    entity_id: input_datetime.xmas_light_start_time
