---
#
# Set the night_time state 
#
alias: System - Night Time Off
initial_state: on
trigger:
  - platform: state
    entity_id: sensor.day_night
    to: 'Tag'
  - platform: homeassistant
    event: start
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: sensor.day_night
      state: 'Tag'
action:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.night_time
      value: 0