---
# Set the default theme on start up of Home Assistant.
#
# This, of course, only affects machine that do not
# have a theme set.
#
alias: System - Night Time On
initial_state: on
trigger:
  - platform: state
    entity_id: sensor.day_night
    to: 'Nacht'
  - platform: homeassistant
    event: start
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: sensor.day_night
      state: 'Nacht'
action:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.night_time
      value: 1