---
# When the alarm gets armed...
#
# TManage Dining down
#
# Dining up early
alias: open_dining_shutters_at_sunrise_partly_workdays
trigger:
  platform: time
  at: "07:40:00"
condition:
  condition: state
  entity_id: binary_sensor.workday_sensor
  state: "on"
action:
  service: cover.set_cover_position
  entity_id: cover.shelly_shsw_25_rolladen_esszimmer 
  data:
    position: 60

