---
# When the alarm gets armed...
#
# TManage Dining down
#

alias: open_dining_shutters_at_sunrise_partly_weekends
trigger:
  platform: time
  at: "09:00:00"
condition:
  condition: state
  entity_id: binary_sensor.workday_sensor
  state: "off"
action:
  service: cover.set_cover_position
  entity_id: cover.shelly_shsw_25_rolladen_esszimmer
  data:
    position: 60
