---
#################################
##    SHUTTER AUTOMATIONS      ##
#################################

# Kitchen up
alias: open_kitchen_shutters_at_sunrise_workdays
trigger:
  platform: time
  at: "07:40:00"
condition:
  condition: state
  entity_id: binary_sensor.workday_sensor
  state: "on"
action:
- service: cover.open_cover
  entity_id:
    - cover.shelly_shsw_25_rolladen_kueche
